// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  AppControllerGetHelloData,
  AppControllerGetHelloResponses,
  AuthControllerLoginData,
  AuthControllerLoginResponses,
  CategoriesControllerCreateData,
  CategoriesControllerCreateResponses,
  CategoriesControllerFindAllData,
  CategoriesControllerFindAllResponses,
  CategoriesControllerRemoveData,
  CategoriesControllerRemoveResponses,
  CategoriesControllerUpdateData,
  CategoriesControllerUpdateResponses,
  PostsControllerCreateData,
  PostsControllerCreateResponses,
  PostsControllerFindAllData,
  PostsControllerFindAllManageData,
  PostsControllerFindAllManageResponses,
  PostsControllerFindAllResponses,
  PostsControllerFindOneData,
  PostsControllerFindOneResponses,
  PostsControllerPublishData,
  PostsControllerPublishResponses,
  PostsControllerRemoveData,
  PostsControllerRemoveResponses,
  PostsControllerUpdateData,
  PostsControllerUpdateResponses,
  TagsControllerCreateData,
  TagsControllerCreateResponses,
  TagsControllerFindAllData,
  TagsControllerFindAllResponses,
  TagsControllerRemoveData,
  TagsControllerRemoveResponses,
  TagsControllerUpdateData,
  TagsControllerUpdateResponses,
  UsersControllerCreateData,
  UsersControllerCreateResponses,
  UsersControllerFindAllData,
  UsersControllerFindAllResponses,
  UsersControllerFindOneData,
  UsersControllerFindOneResponses,
  UsersControllerRemoveData,
  UsersControllerRemoveResponses,
  UsersControllerUpdateData,
  UsersControllerUpdateResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const appControllerGetHello = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerGetHelloData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({
    url: '/api/v1',
    ...options,
  })

/**
 * 用户登录
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthControllerLoginResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 获取所有用户
 */
export const usersControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UsersControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UsersControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options,
  })

/**
 * 创建用户
 */
export const usersControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<UsersControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<UsersControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 删除用户
 */
export const usersControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<UsersControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<UsersControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options,
  })

/**
 * 获取单个用户
 */
export const usersControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UsersControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<UsersControllerFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options,
  })

/**
 * 更新用户
 */
export const usersControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsersControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UsersControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 获取已发布的文章列表
 */
export const postsControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<PostsControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PostsControllerFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/posts',
    ...options,
  })

/**
 * 创建文章
 */
export const postsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostsControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 管理后台获取文章列表
 */
export const postsControllerFindAllManage = <ThrowOnError extends boolean = false>(
  options?: Options<PostsControllerFindAllManageData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PostsControllerFindAllManageResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/manage',
    ...options,
  })

/**
 * 删除文章
 */
export const postsControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<PostsControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}',
    ...options,
  })

/**
 * 获取文章详情
 */
export const postsControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerFindOneData, ThrowOnError>,
) =>
  (options.client ?? client).get<PostsControllerFindOneResponses, unknown, ThrowOnError>({
    url: '/api/v1/posts/{id}',
    ...options,
  })

/**
 * 更新文章
 */
export const postsControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PostsControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 发布文章
 */
export const postsControllerPublish = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerPublishData, ThrowOnError>,
) =>
  (options.client ?? client).patch<PostsControllerPublishResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/posts/{id}/publish',
    ...options,
  })

/**
 * 获取所有标签
 */
export const tagsControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<TagsControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<TagsControllerFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/tags',
    ...options,
  })

/**
 * 创建标签
 */
export const tagsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<TagsControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<TagsControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tags',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 删除标签
 */
export const tagsControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<TagsControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<TagsControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tags/{id}',
    ...options,
  })

/**
 * 更新标签
 */
export const tagsControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TagsControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<TagsControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tags/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 获取所有分类
 */
export const categoriesControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<CategoriesControllerFindAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CategoriesControllerFindAllResponses, unknown, ThrowOnError>({
    url: '/api/v1/categories',
    ...options,
  })

/**
 * 创建分类
 */
export const categoriesControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<CategoriesControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/categories',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * 删除分类
 */
export const categoriesControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CategoriesControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/categories/{id}',
    ...options,
  })

/**
 * 更新分类
 */
export const categoriesControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CategoriesControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<CategoriesControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/categories/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
