// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string
}

export type ApiResponseDto = {
  /**
   * 响应状态码，0 表示成功
   */
  code: number
  /**
   * 响应消息
   */
  message: string
  /**
   * 响应数据
   */
  data: {
    [key: string]: unknown
  }
}

export type PaginatedResponseDto = {
  /**
   * 数据列表
   */
  items: Array<{
    [key: string]: unknown
  }>
  /**
   * 总数
   */
  total: number
  /**
   * 当前页码
   */
  page: number
  /**
   * 每页条数
   */
  limit: number
  /**
   * 总页数
   */
  totalPages: number
}

export type LoginResponseDto = {
  /**
   * 访问令牌
   */
  access_token: string
}

export type LoginDto = {
  /**
   * 用户名
   */
  username: string
  /**
   * 密码
   */
  password: string
}

export type UserResponseDto = {
  /**
   * 用户ID
   */
  id: number
  /**
   * 用户名
   */
  username: string
  /**
   * 用户角色
   */
  role: 'admin' | 'editor'
  /**
   * 创建时间
   */
  created_at: string
  /**
   * 更新时间
   */
  updated_at: string
}

export type CreateUserDto = {
  /**
   * 用户名
   */
  username: string
  /**
   * 密码
   */
  password: string
  /**
   * 用户角色
   */
  role?: 'admin' | 'editor'
}

export type UpdateUserDto = {
  /**
   * 用户名
   */
  username?: string
  /**
   * 密码
   */
  password?: string
  /**
   * 用户角色
   */
  role?: 'admin' | 'editor'
}

export type CategoryResponseDto = {
  /**
   * 分类ID
   */
  id: number
  /**
   * 分类名称
   */
  name: string
  /**
   * 创建时间
   */
  created_at: string
}

export type TagResponseDto = {
  /**
   * 标签ID
   */
  id: number
  /**
   * 标签名称
   */
  name: string
  /**
   * 创建时间
   */
  created_at: string
}

export type PostResponseDto = {
  /**
   * 文章ID
   */
  id: number
  /**
   * 文章标题
   */
  title: string
  /**
   * 文章摘要
   */
  excerpt: {
    [key: string]: unknown
  } | null
  /**
   * 文章内容
   */
  content: string
  /**
   * 文章状态
   */
  status: 'draft' | 'published'
  /**
   * 作者ID
   */
  author_id: number
  /**
   * 分类ID
   */
  category_id: {
    [key: string]: unknown
  } | null
  /**
   * 浏览次数
   */
  view_count: number
  /**
   * 发布时间
   */
  published_at: {
    [key: string]: unknown
  } | null
  /**
   * 创建时间
   */
  created_at: string
  /**
   * 更新时间
   */
  updated_at: string
  /**
   * 作者信息
   */
  author?: UserResponseDto
  /**
   * 分类信息
   */
  category?: CategoryResponseDto | null
  /**
   * 标签列表
   */
  tags?: Array<TagResponseDto>
}

export type CreatePostDto = {
  /**
   * 文章标题
   */
  title: string
  /**
   * 文章摘要
   */
  excerpt?: string
  /**
   * 文章内容
   */
  content: string
  /**
   * 分类 ID
   */
  category_id?: number
  /**
   * 标签名称列表
   */
  tag_names?: Array<string>
}

export type UpdatePostDto = {
  /**
   * 文章标题
   */
  title?: string
  /**
   * 文章摘要
   */
  excerpt?: string
  /**
   * 文章内容
   */
  content?: string
  /**
   * 分类 ID
   */
  category_id?: number
  /**
   * 标签名称列表
   */
  tag_names?: Array<string>
}

export type CreateTagDto = {
  /**
   * 标签名称
   */
  name: string
}

export type UpdateTagDto = {
  /**
   * 标签名称
   */
  name?: string
}

export type CreateCategoryDto = {
  /**
   * 分类名称
   */
  name: string
}

export type UpdateCategoryDto = {
  /**
   * 分类名称
   */
  name?: string
}

export type AppControllerGetHelloData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1'
}

export type AppControllerGetHelloResponses = {
  200: unknown
}

export type AuthControllerLoginData = {
  body: LoginDto
  path?: never
  query?: never
  url: '/api/v1/auth/login'
}

export type AuthControllerLoginResponses = {
  200: ApiResponseDto & {
    data?: LoginResponseDto
  }
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type UsersControllerFindAllData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users'
}

export type UsersControllerFindAllResponses = {
  200: ApiResponseDto & {
    data?: Array<UserResponseDto>
  }
}

export type UsersControllerFindAllResponse =
  UsersControllerFindAllResponses[keyof UsersControllerFindAllResponses]

export type UsersControllerCreateData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/api/v1/users'
}

export type UsersControllerCreateResponses = {
  200: ApiResponseDto & {
    data?: UserResponseDto
  }
}

export type UsersControllerCreateResponse =
  UsersControllerCreateResponses[keyof UsersControllerCreateResponses]

export type UsersControllerRemoveData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/users/{id}'
}

export type UsersControllerRemoveResponses = {
  200: ApiResponseDto & {
    data?: unknown
  }
}

export type UsersControllerRemoveResponse =
  UsersControllerRemoveResponses[keyof UsersControllerRemoveResponses]

export type UsersControllerFindOneData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/users/{id}'
}

export type UsersControllerFindOneResponses = {
  200: ApiResponseDto & {
    data?: UserResponseDto
  }
}

export type UsersControllerFindOneResponse =
  UsersControllerFindOneResponses[keyof UsersControllerFindOneResponses]

export type UsersControllerUpdateData = {
  body: UpdateUserDto
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/users/{id}'
}

export type UsersControllerUpdateResponses = {
  200: ApiResponseDto & {
    data?: UserResponseDto
  }
}

export type UsersControllerUpdateResponse =
  UsersControllerUpdateResponses[keyof UsersControllerUpdateResponses]

export type PostsControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * 页码
     */
    page?: number
    /**
     * 每页数量
     */
    limit?: number
    /**
     * 分类 ID
     */
    category_id?: number
    /**
     * 标签 ID
     */
    tag_id?: number
    /**
     * 搜索关键词
     */
    keyword?: string
  }
  url: '/api/v1/posts'
}

export type PostsControllerFindAllResponses = {
  200: ApiResponseDto & {
    data?: PaginatedResponseDto & {
      items?: Array<PostResponseDto>
    }
  }
}

export type PostsControllerFindAllResponse =
  PostsControllerFindAllResponses[keyof PostsControllerFindAllResponses]

export type PostsControllerCreateData = {
  body: CreatePostDto
  path?: never
  query?: never
  url: '/api/v1/posts'
}

export type PostsControllerCreateResponses = {
  200: ApiResponseDto & {
    data?: PostResponseDto
  }
}

export type PostsControllerCreateResponse =
  PostsControllerCreateResponses[keyof PostsControllerCreateResponses]

export type PostsControllerFindAllManageData = {
  body?: never
  path?: never
  query?: {
    /**
     * 页码
     */
    page?: number
    /**
     * 每页数量
     */
    limit?: number
    /**
     * 分类 ID
     */
    category_id?: number
    /**
     * 标签 ID
     */
    tag_id?: number
    /**
     * 搜索关键词
     */
    keyword?: string
  }
  url: '/api/v1/posts/manage'
}

export type PostsControllerFindAllManageResponses = {
  200: ApiResponseDto & {
    data?: PaginatedResponseDto & {
      items?: Array<PostResponseDto>
    }
  }
}

export type PostsControllerFindAllManageResponse =
  PostsControllerFindAllManageResponses[keyof PostsControllerFindAllManageResponses]

export type PostsControllerRemoveData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/posts/{id}'
}

export type PostsControllerRemoveResponses = {
  200: ApiResponseDto & {
    data?: unknown
  }
}

export type PostsControllerRemoveResponse =
  PostsControllerRemoveResponses[keyof PostsControllerRemoveResponses]

export type PostsControllerFindOneData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/posts/{id}'
}

export type PostsControllerFindOneResponses = {
  200: ApiResponseDto & {
    data?: PostResponseDto
  }
}

export type PostsControllerFindOneResponse =
  PostsControllerFindOneResponses[keyof PostsControllerFindOneResponses]

export type PostsControllerUpdateData = {
  body: UpdatePostDto
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/posts/{id}'
}

export type PostsControllerUpdateResponses = {
  200: ApiResponseDto & {
    data?: PostResponseDto
  }
}

export type PostsControllerUpdateResponse =
  PostsControllerUpdateResponses[keyof PostsControllerUpdateResponses]

export type PostsControllerPublishData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/posts/{id}/publish'
}

export type PostsControllerPublishResponses = {
  200: ApiResponseDto & {
    data?: PostResponseDto
  }
}

export type PostsControllerPublishResponse =
  PostsControllerPublishResponses[keyof PostsControllerPublishResponses]

export type TagsControllerFindAllData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/tags'
}

export type TagsControllerFindAllResponses = {
  200: ApiResponseDto & {
    data?: Array<TagResponseDto>
  }
}

export type TagsControllerFindAllResponse =
  TagsControllerFindAllResponses[keyof TagsControllerFindAllResponses]

export type TagsControllerCreateData = {
  body: CreateTagDto
  path?: never
  query?: never
  url: '/api/v1/tags'
}

export type TagsControllerCreateResponses = {
  200: ApiResponseDto & {
    data?: TagResponseDto
  }
}

export type TagsControllerCreateResponse =
  TagsControllerCreateResponses[keyof TagsControllerCreateResponses]

export type TagsControllerRemoveData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/tags/{id}'
}

export type TagsControllerRemoveResponses = {
  200: ApiResponseDto & {
    data?: unknown
  }
}

export type TagsControllerRemoveResponse =
  TagsControllerRemoveResponses[keyof TagsControllerRemoveResponses]

export type TagsControllerUpdateData = {
  body: UpdateTagDto
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/tags/{id}'
}

export type TagsControllerUpdateResponses = {
  200: ApiResponseDto & {
    data?: TagResponseDto
  }
}

export type TagsControllerUpdateResponse =
  TagsControllerUpdateResponses[keyof TagsControllerUpdateResponses]

export type CategoriesControllerFindAllData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/categories'
}

export type CategoriesControllerFindAllResponses = {
  200: ApiResponseDto & {
    data?: Array<CategoryResponseDto>
  }
}

export type CategoriesControllerFindAllResponse =
  CategoriesControllerFindAllResponses[keyof CategoriesControllerFindAllResponses]

export type CategoriesControllerCreateData = {
  body: CreateCategoryDto
  path?: never
  query?: never
  url: '/api/v1/categories'
}

export type CategoriesControllerCreateResponses = {
  200: ApiResponseDto & {
    data?: CategoryResponseDto
  }
}

export type CategoriesControllerCreateResponse =
  CategoriesControllerCreateResponses[keyof CategoriesControllerCreateResponses]

export type CategoriesControllerRemoveData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/categories/{id}'
}

export type CategoriesControllerRemoveResponses = {
  200: ApiResponseDto & {
    data?: unknown
  }
}

export type CategoriesControllerRemoveResponse =
  CategoriesControllerRemoveResponses[keyof CategoriesControllerRemoveResponses]

export type CategoriesControllerUpdateData = {
  body: UpdateCategoryDto
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/categories/{id}'
}

export type CategoriesControllerUpdateResponses = {
  200: ApiResponseDto & {
    data?: CategoryResponseDto
  }
}

export type CategoriesControllerUpdateResponse =
  CategoriesControllerUpdateResponses[keyof CategoriesControllerUpdateResponses]
